"""m09 budget features

Revision ID: 2ac348055579
Revises: 20260307_0011
Create Date: 2026-03-08 07:56:24.921430

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2ac348055579'
down_revision = '20260307_0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_types', schema=None) as batch_op:
        batch_op.alter_column('lifecycle_state',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('DRAFT', 'VALIDATED', 'ACTIVE', 'DEPRECATED', name='form_type_lifecycle', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_types', schema=None) as batch_op:
        batch_op.alter_column('lifecycle_state',
               existing_type=sa.Enum('DRAFT', 'VALIDATED', 'ACTIVE', 'DEPRECATED', name='form_type_lifecycle', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'"))
    # ### end Alembic commands ###
