RUNTIME_INTEGRATION_FACTORY_ENV = "OMNICLAW_RUNTIME_INTEGRATION_FACTORY"
RUNTIME_DATABASE_URL_ENV = "OMNICLAW_RUNTIME_DATABASE_URL"
RUNTIME_NODE_ID_ENV = "OMNICLAW_RUNTIME_NODE_ID"
RUNTIME_NODE_NAME_ENV = "OMNICLAW_RUNTIME_NODE_NAME"
RUNTIME_OUTPUT_ROOT_ENV = "OMNICLAW_RUNTIME_OUTPUT_ROOT"
RUNTIME_PROMPT_LOG_ROOT_ENV = "OMNICLAW_RUNTIME_PROMPT_LOG_ROOT"
RUNTIME_CALL_SOURCE_ENV = "OMNICLAW_RUNTIME_CALL_SOURCE"

DEFAULT_RUNTIME_INTEGRATION_FACTORY = "omniclaw.runtime_integration.hook:build_runtime_integration"
